
MAKE = make

.PHONY: all
all:
	$(MAKE) -j 1 -C OBJ/STM32F767NUCLEO144_GCC/MAC all

.PHONY: clean
clean:
	$(MAKE) -j 1 -C OBJ/STM32F767NUCLEO144_GCC/MAC clean

.PHONY: realclean
realclean:
	$(MAKE) -j 1 -C OBJ/STM32F767NUCLEO144_GCC/MAC realclean
